// flow-typed signature: 4e40a324efb6c621e19e9e88fb1032c6
// flow-typed version: <<STUB>>/@compositor/kit_v^1.0.47/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@compositor/kit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@compositor/kit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@compositor/kit/dist/Cartesian' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/Catch' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/Color' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/Colorable' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/Debug' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/Diff' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/Fetch' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/Font' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/Frame' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/index' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/Library' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/LiveEditor' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/Markdown' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/Matrix' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/PropsForm' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/Responsive' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/State' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/Style' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/TypeScale' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/ui' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/util' {
  declare module.exports: any;
}

declare module '@compositor/kit/dist/XRay' {
  declare module.exports: any;
}

// Filename aliases
declare module '@compositor/kit/dist/Cartesian.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Cartesian'>;
}
declare module '@compositor/kit/dist/Catch.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Catch'>;
}
declare module '@compositor/kit/dist/Color.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Color'>;
}
declare module '@compositor/kit/dist/Colorable.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Colorable'>;
}
declare module '@compositor/kit/dist/Debug.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Debug'>;
}
declare module '@compositor/kit/dist/Diff.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Diff'>;
}
declare module '@compositor/kit/dist/Fetch.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Fetch'>;
}
declare module '@compositor/kit/dist/Font.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Font'>;
}
declare module '@compositor/kit/dist/Frame.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Frame'>;
}
declare module '@compositor/kit/dist/index.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/index'>;
}
declare module '@compositor/kit/dist/Library.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Library'>;
}
declare module '@compositor/kit/dist/LiveEditor.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/LiveEditor'>;
}
declare module '@compositor/kit/dist/Markdown.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Markdown'>;
}
declare module '@compositor/kit/dist/Matrix.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Matrix'>;
}
declare module '@compositor/kit/dist/PropsForm.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/PropsForm'>;
}
declare module '@compositor/kit/dist/Responsive.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Responsive'>;
}
declare module '@compositor/kit/dist/State.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/State'>;
}
declare module '@compositor/kit/dist/Style.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/Style'>;
}
declare module '@compositor/kit/dist/TypeScale.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/TypeScale'>;
}
declare module '@compositor/kit/dist/ui.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/ui'>;
}
declare module '@compositor/kit/dist/util.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/util'>;
}
declare module '@compositor/kit/dist/XRay.js' {
  declare module.exports: $Exports<'@compositor/kit/dist/XRay'>;
}
